import React from "react";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton,
  SignOutButton,
  RedirectToSignIn
} from '@clerk/nextjs'

import QueryProvider from './providers/QueryProvider'
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import DashboardWrapper from "./dashboardWrapper";
import { auth } from "@clerk/nextjs/server";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
 
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const {userId} = await auth();
  console.log(userId);
  return (
    <ClerkProvider>
    <html lang="en">
      <body className={inter.className}>
      <QueryProvider>
      <SignedIn>
        <DashboardWrapper>{children}</DashboardWrapper>
        </SignedIn>
        <SignedOut>
          
              <RedirectToSignIn />
            </SignedOut>
            </QueryProvider>
      </body>
    </html>
    </ClerkProvider>
  );
}